title: Daniel Shaheen
logo: /nano.jpg
#description: Technical Architect Director at Salesforce 25x Salesforce Certified | Certified Application and System Architect | All Star Ranger | AI Enthusiast
show_downloads: true
theme: jekyll-theme-minimal
